<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/EDA13_%EC%83%81%EB%8C%80_%EC%B5%9C%EA%B7%BC_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [91]:
vs_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_상대_팀투수.csv', encoding='utf-8-sig')
vs_team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_상대_팀타자.csv', encoding='utf-8-sig')
r_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_최근_팀투수.csv', encoding='utf-8-sig')
r_team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_최근_팀타자.csv', encoding='utf-8-sig')

In [92]:
team_data = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_공통.csv', encoding='utf-8-sig')
team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_팀타자.csv', encoding='utf-8-sig')
team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/1차_최종_팀투수.csv', encoding='utf-8-sig')

In [93]:
team_hitter = team_hitter[['OBP',
       'SLG', 'OPS', 'GPA', '타율', 'BABIP', 'ISO', 'HR%', 'K%', 'BB%', 'BBK',
       'wOBA', 'wRAA', 'wRC', 'RC', 'RC27', 'XR', 'SPD', 'SECA', 'PSN']]

In [94]:
team_data = team_data[[
       '실점', '득점', '총득점', '총실점', '평균득점', '평균실점', '승수', '패배수', '승률',
       '피타고리안기대승률', '상대총득점', '상대총실점', '상대평균득점', '상대평균실점', '상대승률',
       '상대피타고리안기대승률', '최근총득점', '최근총실점', '최근평균득점', '최근평균실점', '최근승률',
       '최근피타고리안기대승률', '총합연봉', '평균연봉']]

In [95]:
r_team_hitter_test = r_team_hitter[['최근OBP',
       '최근SLG', '최근OPS', '최근GPA', '최근타율', '최근ISO', '최근BABIP', '최근HR%', '최근K%',
       '최근BB%', '최근BBK', '최근wOBA', '최근wRAA', '최근wRC', '최근RC', '최근RC27', '최근XR',
       '최근SPD', '최근SECA', '최근PSN']]

In [96]:
r_team = pd.concat([r_team_pitcher, r_team_hitter_test, team_data, team_hitter], axis=1)

In [100]:
team_list = []
for year in range(2016, 2021):
  a = r_team[(r_team['일자'] > '{}-05-10'.format(year)) & (r_team['시즌'] == year)]
  team_list.append(a)
r_team = pd.concat(team_list)

In [67]:
r_team

                게임키          일자 팀코드 상대팀코드  ...       XR    SPD   SECA     PSN
306   20160511KTHT0  2016-05-11  HT    KT  ...  154.300  4.892  0.274  20.870
307   20160511KTHT0  2016-05-11  KT    HT  ...  152.286  3.852  0.251  26.963
308   20160511NCHH0  2016-05-11  HH    NC  ...  135.624  3.689  0.238  18.158
309   20160511NCHH0  2016-05-11  NC    HH  ...  154.500  3.940  0.271  19.478
310   20160511OBSK0  2016-05-11  SK    OB  ...  167.574  4.548  0.244  28.070
...             ...         ...  ..   ...  ...      ...    ...    ...     ...
6395  20200719LTSS0  2020-07-19  LT    SS  ...  298.168  4.490  0.241  48.816
6396  20200719OBHT0  2020-07-19  HT    OB  ...  302.194  3.836  0.256  29.506
6397  20200719OBHT0  2020-07-19  OB    HT  ...  364.052  4.500  0.252  40.220
6398  20200719WOSK0  2020-07-19  SK    WO  ...  246.632  4.065  0.220  41.528
6399  20200719WOSK0  2020-07-19  WO    SK  ...  358.756  5.753  0.307  58.959

[4928 rows x 124 columns]

In [37]:
r_team.groupby('결과').mean()

      더블헤더코드        완투        홀드  ...  최근피타고리안기대승률          총합연봉          평균연봉
결과                                ...
D   0.000000  0.000000  0.321429  ...     0.520654  1.078327e+06  16344.092964
L   0.012315  0.004516  0.113711  ...     0.486017  1.037200e+06  15732.087154
W   0.012315  0.020936  0.695402  ...     0.510364  1.048630e+06  15964.029599

[3 rows x 98 columns]

In [69]:
r_team[['최근평균득점','최근OPS']].corr()

          최근평균득점     최근OPS
최근평균득점  1.000000  0.755654
최근OPS   0.755654  1.000000

In [70]:
r_team[['최근평균득점','OPS']].corr()

          최근평균득점       OPS
최근평균득점  1.000000  0.415822
OPS     0.415822  1.000000

In [76]:
r_team[['승률','피타고리안기대승률']].corr()

                승률  피타고리안기대승률
승률         1.00000    0.90949
피타고리안기대승률  0.90949    1.00000

In [55]:
r_team

                게임키          일자 팀코드  ... 최근피타고리안기대승률     총합연봉       평균연봉
306   20160511KTHT0  2016-05-11  HT  ...    0.592933  1058700  15801.493
307   20160511KTHT0  2016-05-11  KT  ...    0.524376   726300  11173.846
308   20160511NCHH0  2016-05-11  HH  ...    0.146193  1454500  19655.405
309   20160511NCHH0  2016-05-11  NC  ...    0.910396   872200  13017.910
310   20160511OBSK0  2016-05-11  SK  ...    0.629340   955500  14051.471
...             ...         ...  ..  ...         ...      ...        ...
6395  20200719LTSS0  2020-07-19  LT  ...    0.446103  1067700  16682.812
6396  20200719OBHT0  2020-07-19  HT  ...    0.326115   998090  15842.698
6397  20200719OBHT0  2020-07-19  OB  ...    0.628253   975000  15476.190
6398  20200719WOSK0  2020-07-19  SK  ...    0.466704   935800  15093.548
6399  20200719WOSK0  2020-07-19  WO  ...    0.481139   885600  14760.000

[4928 rows x 104 columns]

In [97]:
vs_team_hitter = vs_team_hitter[['상대OBP',
       '상대SLG', '상대OPS', '상대GPA', '상대타율', '상대ISO', '상대BABIP', '상대HR%', '상대K%',
       '상대BB%', '상대BBK', '상대wOBA', '상대wRAA', '상대wRC', '상대RC', '상대RC27', '상대XR',
       '상대SPD', '상대SECA', '상대PSN']]

In [98]:
r_team = pd.concat([r_team, vs_team_hitter], axis=1)

In [107]:
r_team[['상대평균득점','상대OPS']].corr()

          상대평균득점     상대OPS
상대평균득점  1.000000  0.751768
상대OPS   0.751768  1.000000

In [108]:
r_team[['상대평균득점','OPS']].corr()

          상대평균득점       OPS
상대평균득점  1.000000  0.348391
OPS     0.348391  1.000000

In [118]:
OB = r_team[(r_team['팀코드'] == 'OB') & (r_team['시즌'] ==2019)].groupby('상대팀코드').mean()[['득점','실점']]

In [125]:
OB

             득점        실점
상대팀코드
HH     5.909091  3.818182
HT     5.500000  3.200000
KT     4.076923  5.615385
LG     5.200000  4.100000
LT     4.363636  3.000000
NC     5.916667  3.416667
SK     4.307692  4.615385
SS     5.384615  2.461538
WO     4.000000  4.600000

In [120]:
OB.columns = ['득점','실점','x']
OB = OB[['득점','실점']]

In [128]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(
    go.Bar(
         x=OB.index,y=OB['득점'],  name='득점'
    )
)
fig.add_trace(
    go.Bar(
         x=OB.index,y=OB['실점'],  name='실점'
    )
)
fig.update_layout(
  {
      "title": {
          "text": "2019년 OB 상대팀별 기록",
          "x": 0.5,
          "y": 0.9,
          "font": {
              "size": 15
          }
      },
      "showlegend": True,
      "xaxis": {
          "title": "득점 및 실점"
        },
    }
)
fig.show()