<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/EDA4_%EA%B0%9C%EC%9D%B8%ED%88%AC%EC%88%98_%EC%84%B8%EC%9D%B4%EB%B2%84_%EB%A7%A4%ED%8A%B8%EB%A6%AD%EC%8A%A4_%ED%95%A9%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
path = './gdrive/My Drive/빅콘테스트2020/데이터/2020빅콘테스트 데이터분석분야-퓨쳐스리그_스포츠투아이_제공데이터(.CSV)_시즌별, 시트별 구분/'

In [3]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [4]:
def load_Data(name):
    years = ['2016','2017','2018','2019','2020']
    name_salt = '2020빅콘테스트_스포츠투아이_제공데이터_'
    PATH = path
    df = pd.DataFrame()
    for year in years:
        if year == '2016':
            df = pd.read_csv(PATH + name_salt + name+'_'+year+'.csv', encoding='CP949')
        else :
            new_df = pd.read_csv(PATH + name_salt + name+'_'+year+'.csv', encoding='CP949')
            df = pd.concat([df, new_df])
    return df

In [5]:
pitcher = load_Data('개인투수')

In [6]:
pitcher

               G_ID   GDAY_DS T_ID  ... P_WHIP_RT  P2_WHIP_RT CB_WHIP_RT
0     20160401HHLG0  20160401   LG  ...  0.000000    1.000000       1.50
1     20160401HHLG0  20160401   LG  ...  0.000000    1.800000       1.50
2     20160401HHLG0  20160401   LG  ...  0.000000    3.000000       0.00
3     20160401HHLG0  20160401   LG  ...  0.818182    1.588235       3.75
4     20160401HHLG0  20160401   HH  ...  0.000000    1.500000       0.00
...             ...       ...  ...  ...       ...         ...        ...
2882  20200719WOSK0  20200719   WO  ...  0.000000    1.000000       2.25
2883  20200719WOSK0  20200719   WO  ...  0.000000    0.000000       0.00
2884  20200719WOSK0  20200719   WO  ...  0.000000    0.000000       1.50
2885  20200719WOSK0  20200719   WO  ...  3.000000    3.000000       0.00
2886  20200719WOSK0  20200719   SK  ...  0.000000    0.000000       0.00

[27804 rows x 38 columns]

In [ ]:
pitcher.columns = new_columns

In [ ]:
new_columns = "게임키 일자 팀코드 상대팀코드 더블헤더코드 초말 선수코드 선발 구원 완투 종료 결과 홀드 이닝*3 투구수 타자 타수 안타 2루타 3루타 홈런 도루 도루 희타 희비 4구 고4 사구 삼진 병살 폭투 보크 실책 실점 자책점 득점권WHIP 2점차이하WHIP 345번타자WHIP"
new_columns = new_columns.split(' ')

In [ ]:
pitcher

                게임키         일자 팀코드 상대팀코드  ...   득점권WHIP 2점차이하WHIP  345번타자WHIP    시즌
0     20160401HHLG0 2016-04-01  LG    HH  ...  0.000000  1.000000        1.50  2016
1     20160401HHLG0 2016-04-01  LG    HH  ...  0.000000  1.800000        1.50  2016
2     20160401HHLG0 2016-04-01  LG    HH  ...  0.000000  3.000000        0.00  2016
3     20160401HHLG0 2016-04-01  LG    HH  ...  0.818182  1.588235        3.75  2016
4     20160401HHLG0 2016-04-01  HH    LG  ...  0.000000  1.500000        0.00  2016
...             ...        ...  ..   ...  ...       ...       ...         ...   ...
2882  20200719WOSK0 2020-07-19  WO    SK  ...  0.000000  1.000000        2.25  2020
2883  20200719WOSK0 2020-07-19  WO    SK  ...  0.000000  0.000000        0.00  2020
2884  20200719WOSK0 2020-07-19  WO    SK  ...  0.000000  0.000000        1.50  2020
2885  20200719WOSK0 2020-07-19  WO    SK  ...  3.000000  3.000000        0.00  2020
2886  20200719WOSK0 2020-07-19  SK    WO  ...  0.000000  0.000000        0.00  2020

[27804 rows x 39 columns]

In [ ]:
pitcher['일자'] = pd.to_datetime(pitcher['일자'],format='%Y%m%d', errors='raise')
pitcher['시즌'] = pitcher['일자'].dt.year

In [ ]:
C_dic = {2016: 3.7732111715557406,
 2017: 3.7201314451138408,
 2018: 3.810512298292339,
 2019: 3.3880686560934894,
 2020: 3.596723044397463}

In [ ]:
def createERA(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    if len(previous) == 0:
      row['평균자책점'] = 0
      return row
    up = previous['자책점'].sum()
    down = previous['이닝*3'].sum() / 3
    if down == 0:
        row['평균자책점'] = 0
        return row
    row['평균자책점'] = (up * 9) / down
    return row

def createRA(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    if len(previous) == 0:
      row['RA/9'] = 0
      return row
    up = previous['실점'].sum()
    down = previous['이닝*3'].sum() / 3
    if down == 0:
        row['RA/9'] = 0
        return row
    row['RA/9'] = (up * 9) / down
    return row

def createERC(row):
    previous = pitcher[pitcher['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    if len(previous) == 0:
      row['ERC'] = 0
      return row
    previous_sum = previous.sum()
    PTB = 0.89 * (1.255 * (previous_sum['안타'] - previous_sum['홈런']) + 4 * previous_sum['홈런']) + 0.475 * (previous_sum['4구'] + previous_sum['사구'] - previous_sum['고4'])
    down = (previous_sum['타자'] * previous_sum['이닝*3'] / 3)
    if down == 0:
      row['ERC'] = 0
      return row
    ERC = 9* ( ((previous_sum['안타'] + previous_sum['4구'] + previous_sum['사구']) * PTB) / down ) - 0.56
    if ERC < 2.24:
      ERC = 9* ( ((previous_sum['안타'] + previous_sum['4구'] + previous_sum['사구']) * PTB) / down ) * 0.75
    row['ERC'] = ERC
    return row

def createFIP(row):
    previous = pitcher[(pitcher['시즌'] == row['시즌']) & (pitcher['선수코드'] == row['선수코드']) & (pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['FIP'] = 0
        return row
    previous_sum = previous.sum()
    down = (previous_sum['이닝*3'] / 3)
    if down == 0 :
      row['FIP'] = 0
      return row
    FIP = (( 13 * previous_sum['홈런'] + 3 * (previous_sum['4구'] + previous_sum['사구'] - previous_sum['고4']) - 2 * previous_sum['삼진']) /down) + C_dic[row['시즌']]
    row['FIP'] = FIP
    return row

def createLOB(row):
    previous = pitcher[(pitcher['시즌'] == row['시즌']) & (pitcher['선수코드'] == row['선수코드']) & (pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['LOB'] = 0
        return row
    previous_sum = previous.sum()
    up = previous_sum['안타'] + previous_sum['4구'] + previous_sum['사구'] - previous_sum['실점']
    down = previous_sum['안타'] + previous_sum['4구'] + previous_sum['사구'] - (1.4 * previous_sum['홈런'])
    if down == 0:
      row['LOB'] = 0
      return row 
    row['LOB'] = up / down
    return row

def createK_HR(row):
    previous = pitcher[(pitcher['시즌'] == row['시즌']) & (pitcher['선수코드'] == row['선수코드']) & (pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['홈런율'] = 0
        row['삼진율'] = 0
        return row
    previous_sum = previous.sum()
    up_HR = previous_sum['홈런'] 
    up_k = previous_sum['삼진']
    down = previous_sum['타자'] - previous_sum['고4']
    if down == 0:
        row['홈런율'] = 0
        row['삼진율'] = 0
        return row
    row['홈런율'] = up_HR / down
    row['삼진율'] = up_k / down
    return row

def create9(row):
    previous = pitcher[(pitcher['시즌'] == row['시즌']) & (pitcher['선수코드'] == row['선수코드']) & (pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['K9'] = 0
        row['BB9'] = 0
        row['HR9'] = 0
        row['KBB'] = 0
        return row
    previous_sum = previous.sum()
    up_K = previous_sum['삼진'] 
    up_BB = previous_sum['4구'] - previous_sum['고4']
    up_HR = previous_sum['홈런']
    down = previous_sum['이닝*3'] / 3
    if down == 0 or up_BB == 0 :
        row['K9'] = 0
        row['BB9'] = 0
        row['HR9'] = 0
        row['KBB'] = 0
        return row
    row['K9'] = up_K / down * 9
    row['BB9'] = up_BB / down * 9
    row['HR9'] = up_HR / down * 9
    row['KBB'] = up_K / up_BB
    return row

In [ ]:
pitcher = pitcher.apply(createERA, axis=1)
pitcher = pitcher.apply(createRA, axis=1)
pitcher = pitcher.apply(createERC, axis=1)
pitcher = pitcher.apply(createFIP, axis=1)
pitcher = pitcher.apply(createLOB, axis=1)
pitcher = pitcher.apply(createK_HR, axis=1)
pitcher = pitcher.apply(create9, axis=1)

In [ ]:
pitcher.tail(20)

                게임키         일자 팀코드  ...       BB9       HR9       KBB
2867  20200719LTSS0 2020-07-19  SS  ...  0.771429  0.771429  7.000000
2868  20200719OBHT0 2020-07-19  HT  ...  1.125000  1.125000  6.000000
2869  20200719OBHT0 2020-07-19  OB  ...  2.054348  1.467391  4.285714
2870  20200719OBHT0 2020-07-19  OB  ...  3.951220  1.975610  1.000000
2871  20200719OBHT0 2020-07-19  OB  ...  2.076923  0.000000  4.333333
2872  20200719OBHT0 2020-07-19  HT  ...  1.025316  0.683544  3.000000
2873  20200719OBHT0 2020-07-19  HT  ...  3.210811  0.729730  1.818182
2874  20200719OBHT0 2020-07-19  OB  ...  4.636364  0.545455  1.264706
2875  20200719OBHT0 2020-07-19  OB  ...  4.418182  0.000000  2.000000
2876  20200719OBHT0 2020-07-19  HT  ...  9.720000  0.540000  1.611111
2877  20200719WOSK0 2020-07-19  WO  ...  1.646341  0.329268  3.800000
2878  20200719WOSK0 2020-07-19  SK  ...  3.453488  1.883721  2.909091
2879  20200719WOSK0 2020-07-19  SK  ...  2.375000  0.625000  3.421053
2880  20200719WOSK0 2020-07-19  WO  ...  1.620000  1.080000  3.333333
2881  20200719WOSK0 2020-07-19  SK  ...  3.417722  0.341772  2.000000
2882  20200719WOSK0 2020-07-19  WO  ...  3.130435  1.173913  2.250000
2883  20200719WOSK0 2020-07-19  WO  ...  3.422535  0.760563  2.333333
2884  20200719WOSK0 2020-07-19  WO  ...  4.821429  0.964286  2.000000
2885  20200719WOSK0 2020-07-19  WO  ...  3.724138  0.000000  1.000000
2886  20200719WOSK0 2020-07-19  SK  ...  6.000000  3.000000  1.000000

[20 rows x 50 columns]

In [ ]:
pitcher.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/EDA4-개인투수_세이버 매트릭스_합본.csv', encoding='utf-8-sig')

In [7]:
pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/EDA4-개인투수_세이버 매트릭스_합본.csv', encoding='utf-8-sig')

In [8]:
pitcher

       Unnamed: 0            게임키          일자  ...       BB9       HR9       KBB
0               0  20160401HHLG0  2016-04-01  ...  0.000000  0.000000  0.000000
1               1  20160401HHLG0  2016-04-01  ...  0.000000  0.000000  0.000000
2               2  20160401HHLG0  2016-04-01  ...  0.000000  0.000000  0.000000
3               3  20160401HHLG0  2016-04-01  ...  0.000000  0.000000  0.000000
4               4  20160401HHLG0  2016-04-01  ...  0.000000  0.000000  0.000000
...           ...            ...         ...  ...       ...       ...       ...
27799        2882  20200719WOSK0  2020-07-19  ...  3.130435  1.173913  2.250000
27800        2883  20200719WOSK0  2020-07-19  ...  3.422535  0.760563  2.333333
27801        2884  20200719WOSK0  2020-07-19  ...  4.821429  0.964286  2.000000
27802        2885  20200719WOSK0  2020-07-19  ...  3.724138  0.000000  1.000000
27803        2886  20200719WOSK0  2020-07-19  ...  6.000000  3.000000  1.000000

[27804 rows x 51 columns]

In [9]:
def createWhip(row):
    previous = pitcher[(pitcher['시즌'] == row['시즌']) & (pitcher['선수코드'] == row['선수코드']) & (pitcher['일자'] < row['일자'])]
    if len(previous) == 0:
        row['whip'] = 0
        return row
    previous_sum = previous.sum()
    up = previous_sum['안타'] + previous_sum['4구']
    down = previous_sum['이닝*3'] / 3
    if down == 0:
      row['whip'] = 0
      return row 
    row['whip'] = up / down
    return row

In [10]:
pitcher = pitcher.apply(createWhip, axis=1)

In [14]:
pitcher = pitcher[['게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드', '초말', '선수코드', '선발',
       '구원', '완투', '종료', '결과', '홀드', '이닝*3', '투구수', '타자', '타수', '안타', '2루타',
       '3루타', '홈런', '도루', '도루.1', '희타', '희비', '4구', '고4', '사구', '삼진', '병살',
       '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP', '2점차이하WHIP', '345번타자WHIP',
       '시즌', '평균자책점', 'RA/9', 'ERC', 'FIP', 'LOB', '홈런율', '삼진율', 'K9', 'BB9',
       'HR9', 'KBB', 'whip']]

In [15]:
pitcher.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/EDA4-개인투수_세이버 매트릭스_합본.csv', encoding='utf-8-sig', index = False)