<a href="https://colab.research.google.com/github/seonghunYang/big_contest2020/blob/master/Model9_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [238]:
import pandas as pd
import numpy as np

In [239]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [240]:
vs_r_team_hitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_상대_팀타자.csv', encoding='utf-8-sig')
vs_r_team_pitcher = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/최근/2차_최종_최근_상대_팀투수.csv', encoding='utf-8-sig')
data = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/한줄에 상대최근 꼴아박기.csv', encoding='utf-8-sig')

In [244]:
data = data[data['초말'] == 1]

In [ ]:
data.to_csv('./gdrive/My Drive/빅콘테스트2020/EDA결과/모델/한줄에 상대최근 꼴아박기.csv', encoding='utf-8-sig', index=False)

In [ ]:
a = vs_r_team_hitter.groupby('게임키').count()
a[a['일자'] == 1].index

In [ ]:
team_code = ['OB', 'WO', 'HT', "LG", 'SS', 'KT', 'LT', 'SK', "HH"]
def team_encoding(row, team_code):
  if row['팀코드'] == team_code:
    row[team_code] = 1
  else:
    if row['팀코드'] != "NC":
      row[team_code] = 0
  return row

def vs_team_encoding(row, team_code):
  if row['상대팀코드'] == team_code:
    row["상대팀{}".format(team_code)] = 1
  else:
    if row['상대팀코드'] != "NC":
      row["상대팀{}".format(team_code)] = 0
  return row


def createHome(row):
  if row['초말'] == 'B':
    row['초말'] = 1
  else:
    row['초말'] = 0
  return row


# 2016 = 0  0 0 0 0 0 0 
year_code = [2017, 2018, 2019, 2020]
def year_encoding(row, year_code):
  if row['시즌'] == year_code:
    row[str(year_code)] = 1
  else:
    if row['시즌'] != 2016:
      row[str(year_code)] = 0
  return row
for team in team_code:
  vs_r_team_hitter = vs_r_team_hitter.apply(team_encoding, axis=1, team_code=team)
  vs_r_team_hitter = vs_r_team_hitter.apply(vs_team_encoding, axis=1, team_code=team)
   
vs_r_team_hitter = vs_r_team_hitter.apply(createHome, axis=1)
for year in year_code:
  vs_r_team_hitter = vs_r_team_hitter.apply(year_encoding, axis=1, year_code=year)

vs_r_team_hitter = vs_r_team_hitter.fillna(0)

In [ ]:
vs_r_team_hitter

      2017  2018  2019  2020  2루타  3루타  4구   HH  ...  초말  타수  타자  타점  팀코드  홈런  희비  희타
0      0.0   0.0   0.0   0.0    2    0   4  0.0  ...   1  42  47   4   LG   1   0   1
1      0.0   0.0   0.0   0.0    2    0   3  1.0  ...   0  46  52   4   HH   0   0   3
2      0.0   0.0   0.0   0.0    2    0   5  0.0  ...   1  30  36   5   NC   2   0   1
3      0.0   0.0   0.0   0.0    3    0   3  0.0  ...   0  34  38   3   HT   1   0   0
4      0.0   0.0   0.0   0.0    5    0   0  0.0  ...   1  36  36   4   SK   1   0   0
...    ...   ...   ...   ...  ...  ...  ..  ...  ...  ..  ..  ..  ..  ...  ..  ..  ..
6326   0.0   0.0   0.0   1.0    1    0   1  0.0  ...   0  29  31   2   LT   1   0   1
6327   0.0   0.0   0.0   1.0    0    1   6  0.0  ...   1  32  38   4   HT   0   0   0
6328   0.0   0.0   0.0   1.0    3    0   2  0.0  ...   0  37  41   8   OB   1   0   0
6329   0.0   0.0   0.0   1.0    0    0   7  0.0  ...   1  30  37   3   SK   0   0   0
6330   0.0   0.0   0.0   1.0    0    0   3  0.0  ...   0  33  37   3   WO   1   0   0

[6331 rows x 89 columns]

In [ ]:
# 게임 1경기 짜리 전부 제거
col = ['20160412NCSS0', '20160414OBHH0', '20160415LGHH0', '20160423HTLT0',
       '20160504OBLG0', '20160505HHSK0', '20160505LTHT0', '20160507HHKT0',
       '20160508LTOB0', '20160511SSLG0', '20160511WOLT0', '20160520OBLT0',
       '20160522KTHH0', '20160529LGOB0', '20160609WONC0', '20160622LTHT0',
       '20160719KTHH0', '20160810SSHH0', '20160824LGOB0', '20160901HTSS0',
       '20170402HTSS0', '20170411HTOB0', '20170427SSHT0', '20170504OBSS0',
       '20170525SKLT0', '20170526SSWO0', '20170608LTNC0', '20170611SKLG0',
       '20170618LGHT0', '20170621OBHT0', '20170629SSHT0', '20170708HTKT0',
       '20170722HHOB0', '20170910WOSK0', '20170916KTHT0', '20170917OBSS0',
       '20171001HTKT0', '20180327SSHT0', '20180331OBKT0', '20180403LTHH0',
       '20180520NCKT0', '20180622OBSS0', '20180623LTLG0', '20180711WOHH0',
       '20180721OBLG0', '20180727HHOB0', '20180805WOKT0', '20180809WOHH0',
       '20180811HTSK0', '20180812HTSK0', '20180911OBLT0', '20180918HTSS0',
       '20180919SKKT0', '20180925LGSK0', '20181003HTSS0', '20190327SSLT0',
       '20190407HHLT0', '20190421SSHH0', '20190508HHSK0', '20190526KTHT0',
       '20190806LGHT0', '20190807WOLT0', '20190825WOSS0', '20200531NCSS0',
       '20200613WONC0', '20200619OBLG0', '20200625NCKT2']

In [ ]:
for key in col:
  vs_r_team_hitter = vs_r_team_hitter[vs_r_team_hitter['게임키'] != key]
  vs_r_team_pitcher = vs_r_team_pitcher[vs_r_team_pitcher['게임키'] != key]

In [ ]:
vs_r_team_pitcher = vs_r_team_pitcher[['게임키', '팀코드','완투', '결과', '홀드', '이닝*3',
       '투구수', '타자', '타수', '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비',
       '4구', '고4', '사구', '삼진', '병살타', '폭투', '보크', '실책', '실점', '자책점', '득점권WHIP',
       '2점차이하WHIP', '345번타자WHIP',  '상대최근평균자책점', '상대최근RA/9', '상대최근ERC',
       '상대최근FIP', '상대최근LOB', '상대최근홈런율', '상대최근삼진율', '상대최근K9', '상대최근BB9',
       '상대최근HR9', '상대최근KBB', '상대최근whip', '상대최근PFR', '상대최근P/G', '상대최근P/IP',
       '상대최근P/PA', '상대최근CYP', '상대최근kwERA', '상대최근K%', '상대최근BB%', '상대최근OAVG',
       '상대최근OOBP', '단타', '상대최근OSLG', '상대최근OOPS', '상대최근투수AB', '상대최근투수HIT',
       '상대최근투수B1B', '상대최근투수B2B', '상대최근투수B3B', '상대최근투수BB', '상대최근투수HR',
       '상대최근투수K', '상대최근투수HBP', '상대최근투수IBB', '상대최근투수SB', '상대최근투수CS',
       '상대최근투수INN', '상대최근득점권WHIP', '상대최근2점차이하WHIP', '상대최근345번타자WHIP',
       '상대최근투수실점']]

In [ ]:
vs_r_team_hitter = vs_r_team_hitter.reset_index()
vs_r_team_pitcher = vs_r_team_pitcher.reset_index()
del vs_r_team_hitter['index']
del vs_r_team_pitcher['index']
data = pd.merge(vs_r_team_hitter, vs_r_team_pitcher, on=['게임키', '팀코드'])
data

      2017  2018  2019  ...  상대최근2점차이하WHIP  상대최근345번타자WHIP  상대최근투수실점
0      0.0   0.0   0.0  ...       0.000000        0.000000  0.000000
1      0.0   0.0   0.0  ...       0.000000        0.000000  0.000000
2      0.0   0.0   0.0  ...       0.000000        0.000000  0.000000
3      0.0   0.0   0.0  ...       0.000000        0.000000  0.000000
4      0.0   0.0   0.0  ...       0.000000        0.000000  0.000000
...    ...   ...   ...  ...            ...             ...       ...
6259   0.0   0.0   0.0  ...       1.876333        1.255667  7.666667
6260   0.0   0.0   0.0  ...       1.291667        1.980000  3.666667
6261   0.0   0.0   0.0  ...       1.777667        1.841333  2.000000
6262   0.0   0.0   0.0  ...       2.423000        1.944333  6.666667
6263   0.0   0.0   0.0  ...       1.255667        1.734000  5.000000

[6264 rows x 159 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6264 entries, 0 to 6263
Columns: 159 entries, 2017 to 상대최근투수실점
dtypes: float64(104), int64(50), object(5)
memory usage: 7.6+ MB

In [ ]:
# col = ["상대최근wRC" , "상대최근득점권타율" , 
#     "상대최근PSN" , "상대최근CS ", "상대최근GDP" , "상대최근SB ", "상대최근득점권타수" , 
#     "상대최근B1B" , "상대최근B2B" , "상대최근wRAA" , 
#     "상대최근HR." , "더블헤더코드" , "상대최근HBP" , "상대최근BB." , 
#     "상대최근BBK" , "상대최근B3B", 
#     "상대최근CYP" , "상대최근투수INN" , 
#     "상대최근LOB" , "상대최근FIP" , "상대최근OAVG" , "상대최근PFR" , 
#     "상대최근KBB" , "상대최근투수CS" , "상대최근2점차이하WHIP" , "상대최근투수B2B" , 
#     "상대최근투수B3B" , "상대최근투수HBP" , "상대최근345번타자WHIP" , 
#     "상대최근kwERA" , "상대최근투수IBB" , "상대최근투수SB" ,
#     ]

cols = ["득점권안타" , "홈런_x" , "희비_x" , "4구_x" , "안타_x" , 
    "잔루" , "사구_x" , "병살타_x" , "도루실패_x" , "타자_x" , "득점권타수" , "초말" , 
    "삼진_x" , "3루타_x" , "고4_x" , "실책_x" , "도루_x",
    "자책점" , "결과" , "투구수" , "실책_y" , "득점권WHIP" , 
    "단타_y" , "홈런_y" , "2루타_y" , "희비_y" , "이닝*3" , "3루타_y" , "사구_y" , "도루실패_y" , 
    "홀드" , "폭투" , "2점차이하WHIP" , "삼진_y" , "보크" , "병살타_y" , "4구_y"]

In [ ]:
def createWIN(row):
  if row['결과'] == 'W':
    row['결과'] = 1
  else:
    row['결과'] = 0
  return row

data = data.apply(createWIN, axis=1)

In [ ]:
data['일자'] = pd.to_datetime(data['일자'], format='%Y-%m-%d')

In [ ]:
data[cols]

      득점권안타  홈런_x  희비_x  4구_x  안타_x  잔루  ...  폭투  2점차이하WHIP  삼진_y  보크  병살타_y  4구_y
0         4     1     0     4     9   8  ...   0      1.286    10   0      1     3
1         3     0     0     3    13  12  ...   1      1.000    11   0      0     4
2         1     2     0     5     9   7  ...   2      1.038    10   0      1     3
3         1     1     0     3     8   7  ...   0      1.696     9   0      1     5
4         3     1     0     0    10   5  ...   0      2.357     7   0      0     4
...     ...   ...   ...   ...   ...  ..  ...  ..        ...   ...  ..    ...   ...
6259      0     1     0     1     6   2  ...   0      1.111     9   0      1     3
6260      4     0     0     6     8   7  ...   0      1.800     4   0      0     2
6261      4     1     0     2    11   6  ...   0      1.000     5   0      1     6
6262      2     0     0     7     6   9  ...   0      1.105     4   0      1     3
6263      1     1     0     3     7   7  ...   2      1.312    10   0      0     7

[6264 rows x 37 columns]

In [ ]:
a =1
rowData = data.iloc[-1 * a]
rowData['결과']

0

In [ ]:
def previousVsData(row, preGame):
  rowData = data[(data['시즌'] == row['시즌']) & (data['팀코드'] == row['팀코드']) & (data['일자'] < row['일자']) & (data['상대팀코드'] == row['상대팀코드'])]
  if len(rowData) <= 2:
    for col in cols:
      row['{}경기전{}'.format(preGame, col)] = 0   
    return row
  rowData = rowData.iloc[-1 * preGame]
  for col in cols:
    row['{}경기전{}'.format(preGame, col)] = rowData[col]
  return row

In [ ]:
data = data.apply(previousVsData, axis=1, preGame=1)

In [ ]:
data = data.apply(previousVsData, axis=1, preGame=2)
data = data.apply(previousVsData, axis=1, preGame=3)

IndexError: ignored

In [ ]:
data = data.apply(previousVsData, axis=1, preGame=3)

In [ ]:
def createWIN(row):
  if row["1경기전결과"] == 0:
    return row
  if row['1경기전결과'] == 'W':
    row['1경기전결과'] = 1
  else:
    row['1경기전결과'] = 0
  return row
data = data.apply(createWIN, axis=1)
data['1경기전결과']

0       0
1       0
2       0
3       0
4       0
       ..
6259    0
6260    0
6261    1
6262    0
6263    1
Name: 1경기전결과, Length: 6264, dtype: int64

In [276]:
def year_filter(data):
  team_list = []
  for year in range(2016, 2021):
    a = data[(data['일자'] > '{}-05-30'.format(year)) & (data['시즌'] == year)]
    team_list.append(a)
  data = pd.concat(team_list)
  return data

data = year_filter(data)

In [277]:
data.columns[:100]

Index(['2017', '2018', '2019', '2020', '2루타_x', '3루타_x', '4구_x', 'HH', 'HT',
       'KT', 'LG', 'LT', 'OB', 'SK', 'SS', 'WO', '게임키', '고4_x', '단타_x',
       '더블헤더코드', '도루_x', '도루실패_x', '득점', '득점권안타', '득점권타수', '득점권타율', '병살타_x',
       '사구_x', '삼진_x', '상대최근AB', '상대최근B1B', '상대최근B2B', '상대최근B3B', '상대최근BABIP',
       '상대최근BB', '상대최근BB%_x', '상대최근BB/K', '상대최근CS', '상대최근GDP', '상대최근GPA',
       '상대최근HBP', '상대최근HIT', '상대최근HR', '상대최근HR%', '상대최근IBB', '상대최근ISO',
       '상대최근K', '상대최근K%_x', '상대최근OBP', '상대최근PA', '상대최근PSN', '상대최근RC',
       '상대최근RC27', '상대최근SB', '상대최근SLG', '상대최근SPD', '상대최근SecA', '상대최근XR',
       '상대최근ops', '상대최근wOBA', '상대최근wRAA', '상대최근wRC', '상대최근득점권안타', '상대최근득점권타수',
       '상대최근득점권타율', '상대최근타율', '상대팀HH', '상대팀HT', '상대팀KT', '상대팀LG', '상대팀LT',
       '상대팀OB', '상대팀SK', '상대팀SS', '상대팀WO', '상대팀코드', '시즌', '실책_x', '안타_x', '일자',
       '잔루', '초말', '타수_x', '타자_x', '타점', '팀코드', '홈런_x', '희비_x', '희타_x', '완투',
       '결과', '홀드', '이닝*3', '투구수', '타자_y', '타수_y', '안타_y', '2루타_y', '3루타_y',
       '홈런_y'],
      dtype='object')

In [285]:
x_data = data[['HH', 'HT',
       'KT', 'LG', 'LT', 'OB', 'SK', 'SS', 'WO','2017', '2018', '2019', '2020','상대팀HH', '상대팀HT', '상대팀KT', '상대팀LG', '상대팀LT',
       '상대팀OB', '상대팀SK', '상대팀SS', '상대팀WO',  
    '1경기전초말', '1경기전삼진_x', '1경기전3루타_x', '1경기전고4_x', '1경기전실책_x', '1경기전도루_x',
       '1경기전자책점', '1경기전결과', '1경기전투구수', '1경기전실책_y', '1경기전득점권WHIP', '1경기전단타_y',
       '1경기전홈런_y', '1경기전2루타_y', '1경기전희비_y', '1경기전이닝*3', '1경기전3루타_y',
       '1경기전사구_y', '1경기전도루실패_y', '1경기전홀드', '1경기전폭투', '1경기전2점차이하WHIP',
       '1경기전삼진_y', '1경기전보크', '1경기전병살타_y', '1경기전4구_y', '2경기전득점권안타', '2경기전홈런_x',
       '2경기전희비_x', '2경기전4구_x', '2경기전안타_x', '2경기전잔루', '2경기전사구_x', '2경기전병살타_x',
       '2경기전도루실패_x', '2경기전타자_x', '2경기전득점권타수', '2경기전초말', '2경기전삼진_x',
       '2경기전3루타_x', '2경기전고4_x', '2경기전실책_x', '2경기전도루_x', '2경기전자책점', '2경기전결과',
       '2경기전투구수', '2경기전실책_y', '2경기전득점권WHIP', '2경기전단타_y', '2경기전홈런_y',
       '2경기전2루타_y', '2경기전희비_y', '2경기전이닝*3', '2경기전3루타_y', '2경기전사구_y',
       '2경기전도루실패_y', '2경기전홀드', '2경기전폭투', '2경기전2점차이하WHIP', '2경기전삼진_y', '2경기전보크',
       '2경기전병살타_y', '2경기전4구_y', '3경기전득점권안타', '3경기전홈런_x', '3경기전희비_x',
       '3경기전4구_x', '3경기전안타_x', '3경기전잔루', '3경기전사구_x', '3경기전병살타_x', '3경기전도루실패_x',
       '3경기전타자_x', '3경기전득점권타수', '3경기전초말', '3경기전삼진_x', '3경기전3루타_x', '3경기전고4_x',
       '3경기전실책_x', '3경기전도루_x', '3경기전자책점', '3경기전결과', '3경기전투구수', '3경기전실책_y',
       '3경기전득점권WHIP', '3경기전단타_y', '3경기전홈런_y', '3경기전2루타_y', '3경기전희비_y',
       '3경기전이닝*3', '3경기전3루타_y', '3경기전사구_y', '3경기전도루실패_y', '3경기전홀드', '3경기전폭투',
       '3경기전2점차이하WHIP', '3경기전삼진_y', '3경기전보크', '3경기전병살타_y', '3경기전4구_y',
       '1경기전득점권안타', '1경기전홈런_x', '1경기전희비_x', '1경기전4구_x', '1경기전안타_x', '1경기전잔루',
       '1경기전사구_x', '1경기전병살타_x', '1경기전도루실패_x', '1경기전타자_x', '1경기전득점권타수',
    ]]
    #    "상대최근wRC" , "상대최근득점권타율" , 
    # "상대최근PSN" , "상대최근CS", "상대최근GDP" , "상대최근SB", "상대최근득점권타수" , 
    # "상대최근B1B" , "상대최근B2B" , "상대최근wRAA" , 
    # "상대최근HR%" , "더블헤더코드" , "상대최근HBP" , "상대최근BB%_x" , 
    # "상대최근BB/K" , "상대최근B3B", 
    # "상대최근CYP" , "상대최근투수INN" , 
    # "상대최근LOB" , "상대최근FIP" , "상대최근OAVG" , "상대최근PFR" , 
    # "상대최근KBB" , "상대최근투수CS" , "상대최근2점차이하WHIP" , "상대최근투수B2B" , 
    # "상대최근투수B3B" , "상대최근투수HBP" , "상대최근345번타자WHIP" , 
    # "상대최근kwERA" , "상대최근투수IBB" , "상대최근투수SB",

y_data = data[['결과']]

In [280]:
x_data.shape

(2016, 166)

In [278]:
data[data['시즌'] == 2020]

      2017  2018  2019  2020  ...  3경기전삼진_y  3경기전보크  3경기전병살타_y  3경기전4구_y
5856   0.0   0.0   0.0   1.0  ...         7       0          3         5
5858   0.0   0.0   0.0   1.0  ...         0       0          0         0
5860   0.0   0.0   0.0   1.0  ...         0       0          0         0
5862   0.0   0.0   0.0   1.0  ...         8       0          0         2
5864   0.0   0.0   0.0   1.0  ...        12       0          0         4
...    ...   ...   ...   ...  ...       ...     ...        ...       ...
6254   0.0   0.0   0.0   1.0  ...         7       0          0         4
6256   0.0   0.0   0.0   1.0  ...         6       0          1         6
6258   0.0   0.0   0.0   1.0  ...         5       0          0         2
6260   0.0   0.0   0.0   1.0  ...         9       0          0         3
6262   0.0   0.0   0.0   1.0  ...        10       0          0         7

[204 rows x 270 columns]

In [287]:
x_data = x_data.values
y_data = y_data.values

In [288]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x_data, y_data, test_size = 0.2 ,shuffle=False
)

In [290]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics

model = Sequential()
model.add(Dense(128, input_shape=(133, ), activation='relu'))
model.add(Dropout(0.5))  
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.5))  
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.5))  
model.add(Dense(64, activation = 'relu'))
model.add(Dropout(0.5))  
model.add(Dense(1, activation= 'sigmoid'))

from keras import optimizers

adam = optimizers.Adam(lr=0.005)
model.compile(loss='binary_crossentropy', optimizer = adam, metrics=[metrics.binary_accuracy])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit(x_train, y_train, validation_split=0.2, verbose = 1,
          batch_size=1, epochs=100, callbacks = [early_stopping])

loss, accuracy = model.evaluate(x_test, y_test, batch_size=1)
print('lose: ', loss)
print('mse: ', accuracy)

y_pred = model.predict(x_test)

Epoch 1/100
1289/1289 [==============================] - 2s 2ms/step - loss: 2.1050 - binary_accuracy: 0.5260 - val_loss: 0.6897 - val_binary_accuracy: 0.5635
Epoch 2/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.7081 - binary_accuracy: 0.5353 - val_loss: 0.6841 - val_binary_accuracy: 0.5666
Epoch 3/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6989 - binary_accuracy: 0.5190 - val_loss: 0.6883 - val_binary_accuracy: 0.5635
Epoch 4/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.7204 - binary_accuracy: 0.5299 - val_loss: 0.6865 - val_binary_accuracy: 0.5635
Epoch 5/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6936 - binary_accuracy: 0.5229 - val_loss: 0.6888 - val_binary_accuracy: 0.5635
Epoch 6/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6939 - binary_accuracy: 0.5330 - val_loss: 0.6878 - val_binary_accuracy: 0.5635
Epoch 7/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6926 - binary_accuracy: 0.5268 - val_loss: 0.6868 - val_binary_accuracy: 0.5635
Epoch 8/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6924 - binary_accuracy: 0.5330 - val_loss: 0.6865 - val_binary_accuracy: 0.5635
Epoch 9/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6926 - binary_accuracy: 0.5330 - val_loss: 0.6872 - val_binary_accuracy: 0.5635
Epoch 10/100
1289/1289 [==============================] - 3s 2ms/step - loss: 0.6918 - binary_accuracy: 0.5330 - val_loss: 0.6857 - val_binary_accuracy: 0.5635
Epoch 11/100
1289/1289 [==============================] - 3s 2ms/step - loss: 0.6934 - binary_accuracy: 0.5283 - val_loss: 0.6862 - val_binary_accuracy: 0.5635
Epoch 12/100
1289/1289 [==============================] - 3s 2ms/step - loss: 0.6926 - binary_accuracy: 0.5330 - val_loss: 0.6880 - val_binary_accuracy: 0.5635
Epoch 13/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6918 - binary_accuracy: 0.5275 - val_loss: 0.6861 - val_binary_accuracy: 0.5635
Epoch 14/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6924 - binary_accuracy: 0.5330 - val_loss: 0.6857 - val_binary_accuracy: 0.5635
Epoch 15/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6916 - binary_accuracy: 0.5330 - val_loss: 0.6860 - val_binary_accuracy: 0.5635
Epoch 16/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6919 - binary_accuracy: 0.5330 - val_loss: 0.6889 - val_binary_accuracy: 0.5635
Epoch 17/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6921 - binary_accuracy: 0.5330 - val_loss: 0.6864 - val_binary_accuracy: 0.5635
Epoch 18/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6921 - binary_accuracy: 0.5330 - val_loss: 0.6867 - val_binary_accuracy: 0.5635
Epoch 19/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6920 - binary_accuracy: 0.5330 - val_loss: 0.6874 - val_binary_accuracy: 0.5635
Epoch 20/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6916 - binary_accuracy: 0.5206 - val_loss: 0.6860 - val_binary_accuracy: 0.5635
Epoch 21/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6920 - binary_accuracy: 0.5330 - val_loss: 0.6876 - val_binary_accuracy: 0.5635
Epoch 22/100
1289/1289 [==============================] - 2s 2ms/step - loss: 0.6922 - binary_accuracy: 0.5330 - val_loss: 0.6896 - val_binary_accuracy: 0.5635
404/404 [==============================] - 0s 883us/step - loss: 0.7316 - binary_accuracy: 0.5396
lose:  0.7316080927848816
mse:  0.5396039485931396

In [300]:
np.where(y_pred == 0.006976545)

(array([296]), array([0]))

In [301]:
x_test[296]

array([  0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         1.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   1.   ,   6.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         4.   ,   1.   , 176.   ,   0.   ,   1.071,   9.   ,   1.   ,
         2.   ,   1.   ,  27.   ,   0.   ,   1.   ,   0.   ,   0.   ,
         0.   ,   1.   ,   9.   ,   0.   ,   0.   ,   4.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   6.   ,   1.   ,   0.   ,   6.   ,
        11.   ,   8.   ,   1.   ,   1.   ,   0.   ,  43.   ,  12.   ])

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc
confusion_matrix = confusion_matrix(y_test,y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test,y_pred)
print(confusion_matrix)
print('recall:' + str(recall) +", precision: " + str(precision) + 'F1-score: ' + str(f1))
roc_auc = roc_auc_score(y_test,y_pred)
roc_auc